name: Update README Benchmarks 🚀

on:
  workflow_dispatch:
  schedule:
    - cron: "15 12 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Benchmarks
        run: |
          echo ${{ secrets.AOC_SESSION }} >> ~/.adventofcode.session
          cargo install aoc-cli
          for i in $(seq -w 1 25); do
            cargo download $i || true
          done
          cargo time --all --store

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README.md"